# Generated by Django 4.2.4 on 2023-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
