# Generated by Django 4.2.4 on 2023-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
