# Generated by Django 4.2.4 on 2023-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
