# Generated by Django 4.2.3 on 2023-08-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50, verbose_name='유저 아이디')),
                ('passwd', models.CharField(max_length=500, verbose_name='유저 비밀번호')),
                ('name', models.CharField(max_length=20, verbose_name='유저 닉네임')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='유저 이메일')),
                ('tel', models.CharField(max_length=20, null=True)),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성 시간')),
            ],
        ),
    ]
